Repository vshn/provider-cloudscale, pull requests merged in 2022-08, with the labels that each got.

#27 Prevent property changes using webhooks
  README.md
  apis/cloudscale/v1/bucket_types.go
  apis/generate.go
  docs/modules/ROOT/pages/tutorials/installation.adoc
  generate_sample.go
  operator/bucketcontroller/observe.go
  operator/bucketcontroller/observe_test.go
  operator/bucketcontroller/setup.go
  operator/bucketcontroller/webhook.go
  operator/bucketcontroller/webhook_test.go
  operator/operator.go
  operator_command.go
  package/crds/cloudscale.crossplane.io_buckets.yaml
  package/webhook/manifests.yaml
  samples/admission.k8s.io_admissionreview.json
  test/local.mk
Labels: enhancement

#28 Document reconciliation process
  README.md
  docs/modules/ROOT/assets/images/.gitkeep
  docs/modules/ROOT/assets/images/bucket-create.drawio.svg
  docs/modules/ROOT/assets/images/bucket-delete.drawio.svg
  docs/modules/ROOT/assets/images/bucket-update.drawio.svg
  docs/modules/ROOT/assets/images/objectsuser-create.drawio.svg
  docs/modules/ROOT/assets/images/objectsuser-delete.drawio.svg
  docs/modules/ROOT/assets/images/objectsuser-update.drawio.svg
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/.gitkeep
  docs/modules/ROOT/pages/explanations/dev/bucket-reconciliation.adoc
  docs/modules/ROOT/pages/explanations/dev/objectsuser-reconciliation.adoc
  docs/modules/ROOT/pages/explanations/dev/provider-mechanics.adoc
Labels: documentation

#30 Add E2E tests with kuttl
  .dockerignore
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/e2e.yml
  Makefile
  README.md
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/kuttl-test.yaml
  test/e2e/provider/00-assert.yaml
  test/e2e/provider/00-install-user.yaml
  test/e2e/provider/01-assert.yaml
  test/e2e/provider/01-install-bucket.yaml
  test/e2e/provider/02-delete.yaml
  test/e2e/tools.go
  test/local.mk
Labels: change

#31 Add deletion policy to remove all existing objects in a bucket
  Makefile.vars.mk
  apis/cloudscale/v1/bucket_types.go
  generate_sample.go
  operator/bucketcontroller/delete.go
  operator/bucketcontroller/update.go
  package/crds/cloudscale.crossplane.io_buckets.yaml
  samples/admission.k8s.io_admissionreview.json
  samples/cloudscale.crossplane.io_bucket.yaml
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/kuttl-test.yaml
  test/e2e/provider/00-assert.yaml
  test/e2e/provider/00-install-user.yaml
  test/e2e/provider/01-assert.yaml
  test/e2e/provider/01-install-bucket.yaml
  test/e2e/provider/02-upload.yaml
  test/e2e/provider/03-delete.yaml
  test/e2e/tools.go
  test/e2e/upload-object.sh
  test/local.mk
Labels: enhancement

#32 Optimize tooling around local dev environment
  .gitignore
  Makefile
  Makefile.vars.mk
  kind/go.mod
  kind/go.sum
  kind/kind.mk
  kind/tools.go
  package/go.mod
  package/go.sum
  package/package.mk
  package/tools.go
  renovate.json
  test/go.mod
  test/go.sum
  test/local.mk
  test/tools.go
Labels: change

#34 Move provider mechanics documentation to Knowledge Base
  README.md
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/dev/provider-mechanics.adoc
Labels: documentation
